# see: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
name: Render LeetCode in Readme
description: Render LeetCode in Readme

# 定义当前步骤参数
inputs:
  user_id:
    description: 用户 ID
    required: true
    default: ''
  displayType:
    description: 显示的数据类型
    required: true
    default: ''

# 向下一个步骤输出参数
# outputs:
#   time: # output will be available to future steps
#     description: 'The message to output'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
        - name: Clear cache
        run: |
          git clean -ffdx
          rm -rf $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: npm install  # You might need yarn install if you use yarn
        
runs:
  using: node16
  main: lib/index.js
